config/routes.rb
Remoteprinter::Application.routes.draw do
  
  # login and logout routes
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/registration' => 'users#new', :as => :registration
  
  # crud resources
  resources :users, :except => :destroy
  resources :sessions
  resources :printers, :only => [:index, :show]
  resources :transactions, :only => [:index, :show]
  resources :jobs, :only => [:index, :show]
  resources :uploaded_files, :only => [:index, :show]

  # dashboard
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  
  # public pages
  match '/how_it_works' => 'public#how_it_works'
  root :to => 'public#index'
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :is_complete, :job_type_id, :name, :pages, :printer_id, :status, :user_id
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  attr_accessible :is_active, :name, :price_per_page
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :amount, :job_id, :type, :user_id
end

app/models/uploaded_file.rb
class UploadedFile < ActiveRecord::Base

  attr_accessor :file
  attr_accessible :amazon_s3_id, :file_type, :name, :user_id, :file
  belongs_to :user

  after_create :upload_to_s3

  def upload_to_s3
    s3 = AWS::S3.new
    b = s3.buckets[APP_CONFIG['amazon_bucket']]

    # here we need to grab the basename of the uploaded file like 'thingamajig.txt'
    # name = file

    # below will be the amazon key. we need to pretty up this code a bit and append the file name, like 'thingamajig.txt'
    amazon_s3_id = user.id.to_s << '-' << created_at.to_s.parameterize.gsub('-', '').gsub('utc', '') # << '-' << name
    b.objects.create(amazon_s3_id, file)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :first_name, :last_name, :password_digest, :password, :password_confirmationU

  validates_presence_of :email, :password, :first_name, :last_name

  has_secure_password
  has_many :transactions
  has_many :jobs
  has_many :uploaded_files

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!
  
  def authenticate_user!
    reset_session unless session[:last_page_load].present? && session[:last_page_load] > 1.day.ago
    session[:last_page_load] = Time.now
    unless logged_in?
      session[:redirect_url] = request.url
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    current_user.present?
  end
  helper_method :logged_in?

  def redirect_back_or_default(default, options = {})
    redirect_to((session[:redirect_url] ? session[:redirect_url] : default), options)
    session[:redirect_url] = nil
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'control_panel'
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  
  skip_before_filter :authenticate_user!
  protect_from_forgery
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate_user!

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "You are now logged in."
      session[:user_id] = user.id
      session[:last_page_load] = Time.now
      redirect_back_or_default root_path
    else
      flash.now[:error] = "Invalid login credentials."
      render :action => :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources
  
  skip_before_filter :authenticate_user!
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Your account was successfully created!"
      redirect_to dashboard_path
    else
      render 'new'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.haml
%h1 Dashboard
%h2 Recent Jobs
- if current_user.jobs.any?
  %ul
    - current_user.jobs.last(5).each do |job|
      %li= job.name
- else
  %p You haven't placed a job yet!
  
%h2 Recent Transactions
- if current_user.transactions.any?
  %ul
    - current_user.transactions.last(5).each do |transaction|
      %li= transaction.amount
- else
  %p You don't have any transactions yet!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remoteprinter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/control_panel.html.haml
!!!
%html
  %head
    %title Blackswirl
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %ul
      %li= link_to 'Logout', logout_path
      %li= link_to 'Jobs', jobs_path
      %li= link_to 'Printers', printers_path
      %li= link_to 'Transactions', transactions_path
      %li= link_to 'Settings', ''
      %li= link_to 'Uploaded Files', uploaded_files_path
    
    = yield

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :password
  = f.submit

app/views/users/new.html.haml
%h1 Create User
= render 'form'